apiVersion: v1
entries:
  kpm-basic-xapp:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2025-09-26T07:54:03.044372673Z"
    description: Standard xApp Helm Chart
    digest: 651ff96af17f157fdcfc912fb41c46cdb3b530d80e2b5b27a7fbb75f3b5c9e39
    name: kpm-basic-xapp
    urls:
    - charts/kpm-basic-xapp-1.0.0.tgz
    version: 1.0.0
generated: "2025-09-26T07:54:03Z"
serverInfo: {}
