apiVersion: v1
entries:
  ric-common:
  - apiVersion: v1
    created: "2025-08-29T10:39:33.888803266Z"
    description: Common templates for inclusion in other charts
    digest: 1856fe0f3222c377a9d35ba9c7c6c74a811c517667f9ddbf824fd6e1916a44f5
    name: ric-common
    urls:
    - charts/ric-common-3.3.2.tgz
    version: 3.3.2
generated: "2025-08-29T10:39:34Z"
serverInfo:
  contextPath: /charts
